### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by shuiRong** [aitexiaoy/Strawberry-Wallpaper#29]
安装后，打开软件时报错

macOS Big Sur 11.1 Beta
Strawberry-Wallpaper 1.4.1 （release下载）

```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from /Users/yangpeng/web/wallpaper-mac/static/img/trayTemplate.png
at createAppTray (webpack:///./src/main/index.js?:147:19)
at appInit (webpack:///./src/main/index.js?:248:9)
at Timeout.setTimeout [as _onTimeout] (webpack:///./src/main/index.js?:72:13)
at ontimeout (timers.js:425:11)
at tryOnTimeout (timers.js:289:5)
at listOnTimeout (timers.js:252:5)
at Timer.processTimers 
```
![image](https://user-images.githubusercontent.com/16076993/101299665-fb154d00-386d-11eb-921d-321d02f4bf24.png)

**Comment by dwzrlp** [comment]
我也是
